version: "3.9"
services:
  ultralight1:
    image: ultralight/cli
    network_mode: "host"
    ports:
      - "8545:8545/tcp"
      - "1-65535/udp"

    environment:
      - rpcport=8545
      - bindAddress=127.0.0.1:5500
      