name: CLI Client Integration Test
on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}/packages/portalnetwork

defaults:
  run:
    working-directory: packages/cli

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cli-devnet-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm pkg set workspaces='["./", "./packages/portalnetwork", "./packages/cli"]' --json
      - run: npm install --workspaces --ignore-scripts
        working-directory: ${{ github.workspace }}

      - run: npm run build --workspaces --if-present
        working-directory: ${{ github.workspace }}

      
      - run: npx ts-node --esm scripts/devnet.ts --numNodes=10 --ip=127.0.0.1 &

      - run: |
          sleep 10 &&
          npx ts-node --esm scripts/seeder.ts --rpcPort=8545 --sourceFile="./blocks200000-210000.json" --numBlocks=3 --numNodes=10
